### ISSUE TITLE
support for set and expire as one call 

### ISSUE THREAD

**Issue by radzhome** [jazzband/django-redis#429] opened 2020-02-11 22:09 UTC
We recently had an issue in django where a key was set but its TTL was 0. The page_cache decorator has a timeout/expiry set to 5 mins (60*50) for all our views. Looks like an intermittent issue where most likely SET was called but something happened to the EXPIRE call. If this was done all in one call using SETEX this would prevent the expiry from being 0, and if the SETEX failed at least it would be set correctly next time the view was cached. Any thoughts or opinions if this is even feasible? Thanks much.

**Comment by WisdomPill** [comment] 2020-05-12 15:09
Hello @radzhome 

I had a look at your issue and it seems to me like the the set call that is performed by the `CacheMiddleware` instance already works as intended.

Let me explain myself in a better way,

`@cache_page` decorator uses `CacheMiddleware` to perform `set` and `get` operations from cache using django proxy class that uses the cache backend of `django_redis` in this case.

The part that uses `cache.set` method here for reference: https://github.com/django/django/blob/d51e090db2110f016dbca1d794c0d379b3df551b/django/middleware/cache.py#L116 calls the cache set method with the timeout already.
That timeout is used in the `SET` command on the client here for reference: https://github.com/jazzband/django-redis/blob/a98b1bfe720e09097e274e906a90f147eea50ea4/django_redis/client/default.py#L156

Furthermore, from redis docs it is reported that the `SET` command with the `EX` option is the same as `SETEX` and that the latter will be deprecated in the future, here for reference: https://redis.io/commands/set#options

```
Note: Since the SET command options can replace SETNX, SETEX, PSETEX, it is possible that in future versions of Redis these three commands will be deprecated and finally removed.
```

Did I understand your issue correctly?

If so, pardon me, I think this is a non-issue and I will close it within the following days.

If you do not answer I will assume that I guessed the nature of the issue.

**Closed** 2020-05-19 17:13 UTC
