### ISSUE TITLE
set_many seems to make a network call per key

### ISSUE THREAD

**Issue by alextousss** [jazzband/django-redis#396] opened 2019-10-22 07:54 UTC
Hello,

I was profiling some code that made heavy use of "set_many". In the source code, it is written that set_many is much faster than setting individual keys.

However, the call graph from cProfile -> KCacheGrind is the following:
https://i.imgur.com/DujxFVP.png

It seems like recv and the whole network stack is used for each key. That would also explain the fact that the function takes 48 ms although a RTT to Redis is ~0.1ms

Maybe am I wrong, I'd really appreciate you correct me so I can understand.

Thank you,

**Comment by WisdomPill** [comment] 2020-05-13 13:38
Hello @alextousss great question! 
It was strange to me at first but then I had a look at the code and ran an experiment using the test suite of `django-redis`. Here is an explanation on the behavior that cProfile gives and why the library works as intended.

The set is done using a pipeline, it means that the commands are not sent until `.execute` is called, here for reference https://github.com/jazzband/django-redis/blob/a98b1bfe720e09097e274e906a90f147eea50ea4/django_redis/client/default.py#L404

The library uses pipeline as a client so that it can use the same logic for timeouts in `.set`.
This is why you see a call to `.set` and `.execute_command` for every key in `.set_many` data parameter.

When `Pipeline` is executed, by default it uses a `MULTI` command for applying changes in a transaction. Also not transactional behavior is available. Anyway, the effective "write" operation is one, **BUT** then after the `MULTI` command is executed, multiple command response have to be parsed, which means that (regardless of the execution in a transaction or not) the method `.parse_response` in the client is called for every command in the pipeline, that will result in multiple `.recv` on the underlying socket.

Here the reference for `.parse_response` responsible for `.recv` 

in execute_pipeline
https://github.com/andymccurdy/redis-py/blob/fa37b8ba7e69c83d0dcd144b6463621d917b5f13/redis/client.py#L3950

and in execute_transcation
https://github.com/andymccurdy/redis-py/blob/fa37b8ba7e69c83d0dcd144b6463621d917b5f13/redis/client.py#L3898

I am closing the issue, please feel free to reopen for further queries or if you have contrasting information about the issue.

**Closed by WisdomPill** 2020-05-13 13:38 UTC
