### ISSUE TITLE
socket timeout option ignored

### ISSUE THREAD

**Issue by tasiotas** [jazzband/django-redis#594] opened 2022-03-26 05:16 UTC
Hi,

django-redis==5.2.0
django==3.2.12
redis:6-alpine
python 3.9.11

I set timeouts for socket connection to 1 sec, but is still takes 30 secs to skip cache and make a query.
Do I understand those options correctly, if Redis is unreachable, django will query db after 1 sec by skipping cache?

I simply turn shutdown Redis service and visit url that makes a query.

Here is my cache setup in settings.py

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
            "SOCKET_CONNECT_TIMEOUT": 1,  # seconds
            "SOCKET_TIMEOUT": 1,  # seconds
        },
    }
}
```

**Comment by WisdomPill** [comment] 2022-03-29 20:29
Hello @tasiotas.

`SOCKET_TIMEOUT` is a parameter for the connection to redis when it does not respond. 
What you are talking about is `timeout` in the django redis backend. 
To change that you need to provide the timeout parameter when you are writing to cache. 
By default django uses 30 seconds, which explains the behavior you are seeing.

I am closing this since it is not a bug, feel free to reply in case I was not clear

**Closed by WisdomPill** 2022-03-29 20:29 UTC
Labels: bug
