### ISSUE TITLE
Django-redis 4.11.0 (latest stable) is incompatible with msgpack 1.0.0 (latest stable)

### ISSUE THREAD

**Issue by fermayo** [jazzband/django-redis#435] opened 2020-02-26 16:08 UTC
When using `django-redis` 4.11.0 with `msgpack` 1.0.0, the following exception happens:

```
TypeError: unpackb() got an unexpected keyword argument 'encoding'
```

This has been fixed in 7aad69ed11c84c4c1ea1f992b01b652ba173a2b1 but there has been no stable release that includes it.

It would be good to have a new stable release that includes this fix as `msgpack` 1.0.0 is now the latest published stable release.

**Comment by jdufresne** [comment] 2020-02-26 16:10
Duplicate of #310

**Closed by jdufresne** 2020-02-26 16:10 UTC
